### ISSUE TITLE
Not able to get it working for asp.net 3.5 / Lotus Domino

### ISSUE THREAD

**Issue by mubaidnovigo** [njupiter/njupiter#9]
I've tried everything possible, to setup nJupiter.DataAccess.Ldap as the membership provider on our intranet based web application built using asp.net 3.5.

Challenges I am facing:

Not able to authenticate the user using the default login webpart (says Your login attempt was not successful. Please try again)

I tried this code and I receive a COMException : "There is no such object on the server."

var ldapMembershipUser = System.Web.Security.Membership.GetUser("username") as LdapMembershipUser;

if (ldapMembershipUser != null) { var givenName = ldapMembershipUser.Attributes["givenName"]; }

I have placed my web.config and the nJupiter.DataAccess.Ldap.config here:

web.config : http://pastebin.com/9XdDnhUH

nJupiter.DataAccess.Ldap.config : http://pastebin.com/WsSEhi98

I have tried all possible permutations and combinations for different values in the XML and i am not able to take it forward. Please guide. I just am not able to connec to the LDAP and authenticate the user or even search for users.

**Comment by mubaidnovigo** [comment]
OK, i downloaded the entire codebase from github, and tried to use the solution instead of using the dll's. I get this error 
The type initializer for 'NestedSingleton' threw an exception. Line 50, nJupiter.DataAccess.Ldap.Configuration.ProviderConfigFactory

Any idea whats cooking up here?

**Comment by twilek** [comment]
"There is no such object on the server" means that either the configured base path or any of the configured attributes does not exist on you server. Since I have no access to your acctual server I can not tell you exactly what is wrong. But I suggest that you investigate if the base path to your user directory realy is o=lrt and that the rdn is named uid and that givenName, sn, title, mail, cn, createTimestamp, ibm-allGroups and member all exists in your directory and that your users realy have the obect class "person" and your groups the object class "group". Since ibm-allGroups is an IBM Tivoli specific attribute it very much sounds like you have some attributes in your configuration that isn't fully correct. I suggest you try to use Softerra LDAP broser http://www.ldapadministrator.com/ to connect to your server and look up what values that is correct for your server.

**Comment by mubaidnovigo** [comment]
Thanks for your reply. 

OK, looks like you may be right. I may still have to tweak all the settings. I am already using the Softerra LDAP browser.

I am trying to access the LDAP with the user lrtguest2. Attached screenshot :
![image](https://cloud.githubusercontent.com/assets/7078807/7344121/a7622f40-ecd1-11e4-9709-3c80fdd6ac45.png)

I commented the ibm-allGroups, and no luck. 

How do i verify that rdn = uid?

**Comment by twilek** [comment]
It most certainly isn't since uid isn't a standard value in Domino. If you check the Domino documentation you notice that it is more likely dominoUNID. The rdn is the attribute that is one to one with the username you want to login with (most comonly a username or an email address). I suggest you read up on your domino server here  https://www.ibm.com/developerworks/lotus/documentation/domino/ and it's LDAP scheme here http://www-01.ibm.com/support/knowledgecenter/SSKTMJ_9.0.1/admin/conf_ldapschema_c.dita?lang=en 

I can unfortunatly not give any help server sepcific issues. If you have specific questions about IBM Lotus Domino I suggest you ask them in their forum because since I have no direct access or any expert knowledge about their producs. To be able to fully configure nJupiter you also have to knwo about basic LDAP concepts (like RDN etc), I suggest you start here http://en.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol
